version: "3.8"

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo

volumes:
  db_data:
