default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  port: <%= Rails.application.credentials.dig(:database, :port) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name, :development) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name, :test) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name, :production) %>
