default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8_general_ci
  pool: 5
  timeout: 5000
  username: paglinawan
  password: salamatpo

development:
  <<: *default
  database: cosmic_library_dev

test:
  <<: *default
  database: cosmic_library_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>
